---
driver:
  name: docker

provisioner:
  name: puppet_apply
  manifests_path: tests
  modules_path: modules
  manifest: init.pp

platforms:
  - name: ubuntu-12.04
    driver_config:
        image: midonet/ubuntu:12.04
  - name: ubuntu-14.04
    driver_config:
        image: midonet/ubuntu:14.04

suites:
  - name: default
    run_list:
    concurrency: true
    attributes:
