---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false

provisioner:
  name: puppet_apply
  manifests_path: test
  modules_path: modules
  hiera_data_path: data
  hiera_config_path: data/hiera.yaml
  manifest: init.pp

platforms:
  - name: centos-7
    driver_config:
        image: midonet/centos:centos7
        privileged: true
        volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
        run_command: /usr/sbin/init
        ssh_timeout: 10
        ssh_retries: 5

suites:
  - name: default
